name: Make Release
on: 
  push:
    tags:
    - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x.x'

      - name: Build
        run: dotnet build -c Release
        
      - name: dotnet publish
        run: |
          dotnet publish "src/LorAuto.Cli" -c Release -r win-x64 -p:PublishSingleFile=true --no-self-contained --nologo -o ${{env.DOTNET_ROOT}}/LorAuto
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: LorAuto
          path: ${{env.DOTNET_ROOT}}/LorAuto
      
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: LorAuto
          tag: ${{ github.ref }}
          name: Release ${{ github.ref }}
          makeLatest: true
          generateReleaseNotes: true
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
